version: '3.8'

services:
  my-job:
    build: ./app
    depends_on:
      - my-db
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PASSWORD=${MY_PASSWORD}
      
  my-db:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
 
volumes:
  redis_data:
